[package]
name = "kubelet"
version = "0.1.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"

[dependencies]
async-trait = "0.1"
dirs = "2.0"
anyhow = "1.0"
futures = { version = "0.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "0.13", default-features = false, features = ["stream"] }
log = "0.4"
reqwest = "0.10"
tokio  = { version = "0.2", features = ["fs", "stream", "macros"] }
kube = { version = "0.32.0", git = "https://github.com/peterhuene/kube-rs", rev = "feat/token_refresh" }
k8s-openapi = { version = "0.7", default-features = false, features = ["v1_17"] }
chrono = { version = "0.4", features = ["serde"] }
structopt = { version = "0.3", features = ["wrap_help"], optional = true }
hostname = "0.3"
native-tls = "0.2"
tokio-tls = "0.3"
thiserror = "1.0"
lazy_static = "1.4"
oci-distribution = { path = "../oci-distribution", version = "0.1.0" }
rpassword = "4.0"

[features]
cli = ["structopt"]
docs = ["cli"]

[package.metadata.docs.rs]

rustdoc-args = ["--cfg", "feature=\"docs\""]
